// ============================================================
// ВСЕ ПОДПИСКИ (110 штук) — полностью обновлено
// ============================================================
const allSubscriptions = [
    // ГРИБЫ 1-25
    { name: "Гриб #1", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/1.txt", type: "main" },
    { name: "Гриб #2", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/2.txt", type: "main" },
    { name: "Гриб #3", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/3.txt", type: "main" },
    { name: "Гриб #4", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/4.txt", type: "main" },
    { name: "Гриб #5", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/5.txt", type: "main" },
    { name: "Гриб #6", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/6.txt", type: "main" },
    { name: "Гриб #7", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/7.txt", type: "main" },
    { name: "Гриб #8", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/8.txt", type: "main" },
    { name: "Гриб #9", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/9.txt", type: "main" },
    { name: "Гриб #10", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/10.txt", type: "main" },
    { name: "Гриб #11", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/11.txt", type: "main" },
    { name: "Гриб #12", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/12.txt", type: "main" },
    { name: "Гриб #13", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/13.txt", type: "main" },
    { name: "Гриб #14", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/14.txt", type: "main" },
    { name: "Гриб #15", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/15.txt", type: "main" },
    { name: "Гриб #16", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/16.txt", type: "main" },
    { name: "Гриб #17", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/17.txt", type: "main" },
    { name: "Гриб #18", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/18.txt", type: "main" },
    { name: "Гриб #19", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/19.txt", type: "main" },
    { name: "Гриб #20", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/20.txt", type: "main" },
    { name: "Гриб #21", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/21.txt", type: "main" },
    { name: "Гриб #22", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/22.txt", type: "main" },
    { name: "Гриб #23", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/23.txt", type: "main" },
    { name: "Гриб #24", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/24.txt", type: "main" },
    { name: "Гриб #25", url: "https://raw.githubusercontent.com/hiztin/VLESS-PO-GRIBI/main/deploy/subscriptions/25.txt", type: "main" },

    // ОСТАЛЬНЫЕ ПОДПИСКИ (85 штук)
    { name: "LimeVPN", url: "https://raw.githubusercontent.com/LimeHi/LimeVPN/refs/heads/main/LimeVPN.txt?v=1", type: "main" },
    { name: "Mygala VPN", url: "https://raw.githubusercontent.com/btsk161/Freeinternet_byMygalaru.github.io/refs/heads/main/premium.txt", type: "main" },
    { name: "AllVPN", url: "https://sub.fawlok.me/", type: "main" },
    { name: "GhostwlVPN", url: "https://imrekpaladinov-web.github.io/vpn/vpn.html", type: "main" },
    { name: "Wi-Fixex", url: "https://raw.githubusercontent.com/Temnuk/naabuzil/refs/heads/main/wifi", type: "main" },
    { name: "LTExex", url: "https://raw.githubusercontent.com/Temnuk/naabuzil/refs/heads/main/whitelist_full", type: "wl" },
    { name: "RestlyconnectVPN", url: "https://panell.restlyconnect.mooo.com/api/sub/KzGzw3toDCP1NCZF", type: "main" },
    { name: "SolarVPN", url: "https://raw.githubusercontent.com/twempyasha/twempy-vpn/main/solarvpn.txt", type: "main" },
    { name: "CVEDCVPN", url: "https://gist.githubusercontent.com/pidarasuebisov-afk/529f9f13b4f051b9cf2c43ea4e61d840/raw/aece9ba3dd2fbc3435d2e37092d469e2ab6c6e7d/TG%2520CVEDC%2520VPN%2520LTE", type: "main" },
    { name: "MifaVPN", url: "https://mifa.world/vless", type: "main" },
    { name: "ShadowlosVPN", url: "https://corelinker.ru/api/dynamic_config?user_id_hash=aa844bc3a93054413d50eb6ced4df9808a7fda3360d2cf3973deba48083de7af#Shadowlos", type: "main" },
    { name: "ShadeVPN", url: "https://vpn.tgflovv.ru:8443/free-speed/fec5cb66-6aec-4ff8-8f21-54610c213f7f", type: "main" },
    { name: "ShadeWL", url: "https://vpn.tgflovv.ru:8443/free-white-ru/fec5cb66-6aec-4ff8-8f21-54610c213f7f", type: "wl" },
    { name: "MeraLTE", url: "https://MeraVPN.cc.cd/lte", type: "main" },
    { name: "MeraWL", url: "https://MeraVPN.cc.cd/flask", type: "wl" },
    { name: "MeraVPN", url: "https://MeraVPN.cc.cd/default", type: "main" },
    { name: "ZotusVPN", url: "https://vpn.zotus.ru/sub.php", type: "main" },
    { name: "FreeCfgVPN", url: "https://translate.yandex.ru/translate?url=https://raw.githubusercontent.com/Ilyacom4ik/free-v2ray-2026/refs/heads/main/subscriptions/FreeCFGHub1.txt", type: "main" },
    { name: "SemqkaVPN", url: "https://tinyurl.com/SemqkaVLESS", type: "main" },
    { name: "Catle'r", url: "https://gitverse.ru/api/repos/Catlerok_glasha/catwhiteMIRROR/raw/branch/master/Script-catler.txt", type: "main" },
    { name: "Catle'rWL", url: "https://gitverse.ru/api/repos/Catlerok_glasha/catwhiteMIRROR/raw/branch/master/configs.txt", type: "wl" },
    { name: "CatVPN", url: "https://raw.githubusercontent.com/ShadowException/VPN/refs/heads/main/configs/VPN-cat", type: "main" },
    { name: "Luxxuria", url: "https://raw.githubusercontent.com/luxxuria/harvester/refs/heads/main/non_ru.txt", type: "main" },
    { name: "AccarVPN", url: "https://accargame.cfd/sub/o2MaHP2kvzILzAb7", type: "main" },
    { name: "AirLinkVPN", url: "https://raw.githubusercontent.com/AirLinkVPN1/AirLinkVPN/refs/heads/main/rkn_white_list", type: "wl" },
    { name: "ФлагманVPN", url: "https://ssconnect.app/link?url_ha=happ%3A%2F%2Fcrypt4%2FJ9QAEyIfI27fzZ4edWTdilLhTXdUkiKUUKrsinWaTjkwjO3XabwvLNIpYH%2FLBUDafuLDD8IyVkJuO6Q%2BuptbQ7AqYQNFSA09Ym4PVhRp05fHLlZFSBLNuXbA%2Bv5Ynn195Lzu9wnhHAbSL8TLRHyRMYSLU2Vsxj2ud%2Be0%2FS5ShH8QsGvomhZEd7SpQO1UFJatjial4HAg%2FlIwl2A1LkhiKSsGy6OOryX82fadjrzkoQ9wjC6ZfznAMgO8kBZ7TV85YbKQMxJjrKWkZysr8P4ZWKutL3k4JP0UCwJwO5riwl%2F68Gk4yI441qAgRvEklYY%2Fr%2BKzaOZcaDmGp3rzj0JPpjubfahMPSoZT4aVG7DWLGYMCkQk%2FpFwe3pRZQn2Gb2IrK%2BFCd1eTQTqatCwjAtFDGsyxHtiRe%2BEgD8OUgDhNf0BVLxBM4f8%2BwZuTvvCdsS%2FYSzGiR0WecvOtHlp42DH8kHCJ1xivCSzSpyXzCEYQOMMUOWMg0slyvHLby19IfHravTJNAQErrAUBCSjF3O%2B5bE%2FgFqSghCznUAkF5fuECZSm2ozCBVPl1UBdpG048FTHZc6zr%2FPB9ZK5qLlDjVjnULV4RHLqGH92b1QPcKvxDdJ%2F05vgkAwnxD45%2FPFNcB1%2BAsI1svg5QlOckrDr2rYVOyNUk83umCgUYEIIyvnXvU%3D", type: "main" },
    { name: "WSWPN", url: "https://raw.githubusercontent.com/WSJuJuB01/WS_Parser/refs/heads/main/subscription.txt", type: "main" },
    { name: "BebeVPN", url: "https://gertest3.nekosocks.com:8888/subx/SUQxMDQ4OTQsMTc3NzQ4MzQ0Mwu4jjU-uO7u", type: "main" },
    { name: "SwordwareVPN", url: "https://raw.githubusercontent.com/mbelspb-gif/fefdfd/refs/heads/main/Swordware.net", type: "main" },
    { name: "ХаляваVPN", url: "https://gist.githubusercontent.com/myPHOdq23453212345676tdgedse/9733d29a0c7c3f70d67b41ad9e829cff/raw/vpn.txt", type: "main" },
    { name: "TreeVPN", url: "https://raw.githubusercontent.com/likzil/vless1/main/Treetcpvpn", type: "main" },
    { name: "NiyakwayWL", url: "https://gitverse.ru/api/repos/Niyakwi/Kfg-analyzer/raw/branch/master/new_file", type: "wl" },
    { name: "AetrisVPNWL", url: "https://gitverse.ru/api/repos/flaafix/AetrisVPN/raw/branch/master/AetrisVPN.txt", type: "wl" },
    { name: "ScalaVPN", url: "https://tinyurl.com/scalavpnbot", type: "main" },
    { name: "AWCFG", url: "https://raw.githubusercontent.com/ssavnayt/AWCFG-CONFIG-LIST/refs/heads/main/Configs-AUTO.txt", type: "main" },
    { name: "VlessDo", url: "https://raw.githubusercontent.com/opti4riponty-arch/VLESS-Co/refs/heads/main/VLESS%20%26%20Co", type: "main" },
    { name: "WLRUS", url: "https://gitverse.ru/api/repos/RUVIPIEN/russian-white-bolt/raw/branch/master/VPNMIRRORS/nekobox/ByWarm_Selected_6ac883.txt", type: "wl" },
    { name: "KiryaWL", url: "https://gitverse.ru/api/repos/RUVIPIEN/russian-white-bolt/raw/branch/master/VPNMIRRORS/nekobox/Kirya_White_Lists_25_7c3d65.txt", type: "wl" },
    { name: "YaltaVPN", url: "https://raw.githubusercontent.com/YaltaVPN/YaltaVPNConfigs/refs/heads/main/YaltaVPN%20-%20Subscription.txt", type: "main" },
    { name: "AeryxWIFI", url: "https://tinyurl.com/PodpiskaWIFI124D", type: "main" },
    { name: "AeryxLTE", url: "https://tinyurl.com/AeryxVPNyandexua", type: "main" },
    { name: "ChkavVPN", url: "https://gist.githubusercontent.com/chkav/b1a93c05a33118f826964f308b59b6f6/raw/7d6e0e081837fdc393e5f727a7c4bc0c7cbc5d9f/ChkavVPN", type: "main" },
    { name: "HappKeys", url: "https://gist.githubusercontent.com/HappKeysHub/cc8527d0a806ca426ab4468edac87524/raw/65d3cbfbc2fd3c5d681f859edd54c5f5fc46d3a7/HappKeysHub", type: "main" },
    { name: "AkresVPN", url: "https://vpn.akres.fun/all", type: "main" },
    { name: "RemiucVPN", url: "https://github.com/Remiuc0ff/Hiddifycode/raw/refs/heads/main/Owner-@remiuc", type: "main" },
    { name: "TerikVPN", url: "https://github.com/terik21/HiddifySubs-VlessKeys/raw/refs/heads/main/4Thur", type: "main" },
    { name: "TerikWL", url: "https://github.com/terik21/HiddifySubs-VlessKeys/raw/refs/heads/main/RU_other", type: "wl" },
    { name: "TerikWL2", url: "https://github.com/terik21/HiddifySubs-VlessKeys/raw/refs/heads/main/WhiteKeys", type: "wl" },
    { name: "SelvaGuardWL", url: "https://gist.github.com/lsncococososo-rgb/89942bd29d24c54097ba9b580e50b782/raw/39949a0d333d8040d198719cc35e2ccd56f407e2/BCgreen", type: "wl" },
    { name: "Nzeavpn", url: "https://raw.githubusercontent.com/nzea243/ikoV31tud_vpn/refs/heads/main/tri_228.txt", type: "main" },
    { name: "GreenRu", url: "https://gist.github.com/lsncococososo-rgb/fb03c199f603fe22843c5d8a2e688a57/raw/33f9c10297dd6963e060568512842a6c76e9eeee/Green_vpn", type: "main" },
    { name: "GreenGe", url: "https://gist.github.com/lsncococososo-rgb/d0b7499c853ccc19ee16524798d15606/raw/b9f469552fd96d3c273723d84eea41acfd93fc8c/Germany_Green", type: "main" },
    { name: "GreenFin", url: "https://gist.github.com/lsncococososo-rgb/06cd1dbfcd34ff51cb45acd8fb9b681c/raw/cdf3916263e890c11cd96eb5400702ac6f11dc52/Finland_Green", type: "main" },
    { name: "GreenWL", url: "https://gist.github.com/lsncococososo-rgb/89942bd29d24c54097ba9b580e50b782/raw/39949a0d333d8040d198719cc35e2ccd56f407e2/BCgreen", type: "wl" },
    { name: "NotorWL", url: "https://raw.githubusercontent.com/Ai123999/WhiteKeys/refs/heads/main/WhiteKeys", type: "wl" },
    { name: "NotorRU", url: "https://raw.githubusercontent.com/Ai123999/RU_other/refs/heads/main/RU_other", type: "main" },
    { name: "NotorVPN", url: "https://raw.githubusercontent.com/Ai123999/1Mond/refs/heads/main/1Mond_Notorgamers", type: "main" },
    { name: "KrotWL", url: "https://raw.githubusercontent.com/kort0881/vpn-vless-configs-russia/main/githubmirror/clean/vless.txt", type: "wl" },
    { name: "Prosvet", url: "https://key.prosvet.best/sub", type: "main" },
    { name: "XyexVPN", url: "https://gist.githubusercontent.com/moksim76/92204ebd574b39d712ec71152eb15a69/raw/193993d7bf80c2a5f0a76ec65dc1914f737a5dd3/gistfile1.txt", type: "main" },
    { name: "VSPXQUOR", url: "https://gist.githubusercontent.com/VSPBOOST/d84dcf89bf31012a96ee60a9eb73b852/raw/4f6af123b4a0251806b89958c845666268283c5a/gistfile1.txt", type: "main" },
    { name: "VSPXQUORWL", url: "https://vspsub.onrender.com/get/my1hr", type: "wl" },
    { name: "Ghostping", url: "https://s.id/anon_gl", type: "main" },
    { name: "ghostanony", url: "https://s.id/anon_gl", type: "main" },
    { name: "RTPvpn", url: "https://raw.githubusercontent.com/VSd223/vpn/refs/heads/main/vpn", type: "main" }
];
